### ISSUE TITLE
capi_return is NULL , numpy.linalg.LinAlgError: Singular matrix 

### ISSUE THREAD

**Issue by Max1967** [Bharath2/Quadrotor-Simulation#1]
Hello, its a nice project you are doing, thank you for sharing it with community.
When i'm using the Trajectory generation and control example on the README file everything is fine, but when i want to use RRT waypoints as input i get this error:

capi_return is NULL
Call-back cb_calcfc_in__cobyla__user__routines failed.
Traceback (most recent call last):
  File "/home/ROS/Quadrotor-Simulation/runsim.py", line 56, in <module>
    traj = trajGenerator(waypoints,max_vel = 10,gamma = 1000000)
  File "/home/ROS/Quadrotor-Simulation/TrajGen/trajGen.py", line 16, in __init__
    self.optimize()
  File "/home/ROS/Quadrotor-Simulation/TrajGen/trajGen.py", line 28, in optimize
    T = optimize.minimize(self.get_cost,Tmin, method="COBYLA",constraints= ({'type': 'ineq', 'fun': lambda T: T-Tmin}))['x']
  File "/home/ROS/.local/lib/python3.6/site-packages/scipy/optimize/_minimize.py", line 623, in minimize
    return _minimize_cobyla(fun, x0, args, constraints, **options)
  File "/home/ROS/.local/lib/python3.6/site-packages/scipy/optimize/cobyla.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "/home/ROS/.local/lib/python3.6/site-packages/scipy/optimize/cobyla.py", line 262, in _minimize_cobyla
    dinfo=info)
  File "/home/ROS/.local/lib/python3.6/site-packages/scipy/optimize/cobyla.py", line 252, in calcfc
    f = fun(x, *args)
  File "/home/ROS/Quadrotor-Simulation/TrajGen/trajGen.py", line 21, in get_cost
    coeffs,cost = self.MinimizeSnap(T)
  File "/home/ROS/Quadrotor-Simulation/TrajGen/trajGen.py", line 40, in MinimizeSnap
    invA = LA.inv(A)
  File "<__array_function__ internals>", line 6, in inv
  File "/home/ROS/.local/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 546, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "/home/ROS/.local/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 88, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix

I'm using numpy-1.19.5 and scipy-1.5.4
Thanks in advanced.

**Comment by Bharath2** [comment]
Hi, sorry for late reply.

I have updated the readme and runsim.py files. 

If any two consecutive waypoints have the same (x,y,z) coordinates, you will get this  "Singular matrix"  error.

And also my scipy version is 1.1.0,  If that made any difference.

Hope this helps.
Feel free to contribute to any part of the code.

**Comment by Bharath2** [comment]
There was a typo in rrt.py file. I fixed it.

I will close this issue if you confirm that it's working.

**Comment by Max1967** [comment]
Hi, Thank you for your reply.
I noticed the "singular matrix" error was happening cause of duplicate waypoint in the end of "waypoints" array after RRTStar, so i just used: 
waypoints = np.delete(waypoints,(np.shape(waypoints)[0]-1), axis=0)
before "trajGenerator" in "runsim.py" for removing the last item in the array and it worked.
Then i saw your reply and clone your project again,i didn't check what you did yet, but i tried your new update and it is working perfectly with your changes. 
Thanks again.
